### ISSUE TITLE
LTK seems overly reliant on the WebWorker API

### ISSUE THREAD

**Issue by no-identd** [laffra/ltk#7]
Step 1: install & activate [JShelter](https://jshelter.org/)
Step 2: Go to https://laffra.github.io/ltk/?tab=9
Step 3: observe how it's broken
Step 4: switch JShelter's WebWorker blocking from the default "Remove" to "Strict"
Step 5: reload the page and note how large parts of it now work despite JShelter's strict mode actually precluding WebWorker functionality
Step 6: ???

**Comment by laffra** [comment]
LTK uses PyScript, which uses Workers with Atomics and it's all standard Web technologies ... it's not a security issue, it's just how SharedArrayBuffer projects work ... all of them.

**Comment by WebReflection** [comment]
There is nothing inherently wrong in using Web Workers, it's just standard API.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API

Atomics require workers too or are basically useless: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics

SharedArrayBuffer requires special headers the site controls.

Stating "*your project uses WebWorker*" means nothing:

  * it's not a security threat
  * it's not a bad practice, actually it helps non blocking the main thread ever so that tabs can always be closed too
  * it's part of the W3C and WHATWG standard

It would be nice to understand the context of the projects you claim insecure, @no-identd, this way of FUD looks very counter-productive for the Web community.
